import turtle
turtle.left(45)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(180)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.hideturtle()


turtle.penup()
turtle.goto(-180, -180)
turtle.showturtle()
turtle.pendown()
turtle.done()